// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConfirmSetupAndStart():Promise<void>;

export function GetSettings():Promise<main.Config>;

export function GetSettingsFolder():Promise<string>;

export function GetStatus():Promise<main.EngineSnapshot>;

export function GetVersion():Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenSettingsFolder():Promise<void>;

export function Quit():Promise<void>;

export function RegeneratePinCode():Promise<main.Config>;

export function SaveSettings(arg1:main.Config):Promise<main.Config>;

export function ShowAboutPage():Promise<void>;

export function ShowMirroredScreen():Promise<boolean>;

export function ShowSettingsPage():Promise<void>;

export function ShowWindow():Promise<void>;

export function StartMirroring():Promise<void>;

export function StopMirroring():Promise<void>;
