// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogsFolder() {
  return window['go']['main']['App']['GetLogsFolder']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSettingsFolder() {
  return window['go']['main']['App']['GetSettingsFolder']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenLogsFolder() {
  return window['go']['main']['App']['OpenLogsFolder']();
}

export function OpenSettingsFolder() {
  return window['go']['main']['App']['OpenSettingsFolder']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RegeneratePinCode() {
  return window['go']['main']['App']['RegeneratePinCode']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowAboutPage() {
  return window['go']['main']['App']['ShowAboutPage']();
}

export function ShowMirroredScreen() {
  return window['go']['main']['App']['ShowMirroredScreen']();
}

export function ShowSettingsPage() {
  return window['go']['main']['App']['ShowSettingsPage']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartMirroring() {
  return window['go']['main']['App']['StartMirroring']();
}

export function StopMirroring() {
  return window['go']['main']['App']['StopMirroring']();
}
